[package]
name = "normalizer"
version = "0.1.0"
edition = "2021"

[lib]
name = "normalizer"
path = "src/normalizer/lib.rs"

[dependencies]
winit = "0.26.1"
wgpu = "0.12.0"
pollster = "0.2.5"
dirs = "4.0.0"
lazy_static = "1.4.0"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
serde_derive = "1.0.136"
env_logger = "0.9"
log = "0.4.14"
