[package]
name = "normalizer"
version = "0.1.0"
authors = ["Vladimir Zarypov <krre31@gmail.com>"]
edition = "2021"

[lib]
name = "normalizer"
path = "src/normalizer/lib.rs"

[dependencies]
dirs = "5.0.1"
pollster = "0.3.0"
serde = { version = "1.0.208", features = ["derive"] }
serde_json = "1.0.125"
wgpu = "22.1.0"
winit = "0.30.5"
