[package]
name = "normalizer"
version = "0.1.0"
authors = ["Vladimir Zarypov <krre31@gmail.com>"]
edition = "2021"
description = "IDE for developing of Norm projects"
repository = "https://github.com/krre/normalizer"

[lib]
name = "normalizer"
path = "src/normalizer/lib.rs"

[dependencies]
antiq = { path = "../antiq" }
dirs = "5.0.1"
pollster = "0.4.0"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.134"
wgpu = "23.0.1"
winit = "0.30.7"
